# Generated by Django 6.1.1 on 2026-09-19 13:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videojuegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoCompetitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_regla_participantes', models.CharField(choices=[('ELIMINACION_DIRECTA', 'Eliminación directa')], default='ELIMINACION_DIRECTA', max_length=30)),
                ('min_participantes', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_participantes', models.PositiveIntegerField(default=128, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Público'), ('OFICIAL', 'Oficial')], max_length=10)),
                ('tipo_participante', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('EQUIPO', 'Equipo')], default='INDIVIDUAL', max_length=10)),
                ('tamano_equipo', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_participantes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='torneos/')),
                ('reglas', models.TextField(blank=True)),
                ('codigo_acceso', models.CharField(blank=True, max_length=100)),
                ('nivel_minimo', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_apertura_inscripciones', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre_inscripciones', models.DateTimeField(blank=True, null=True)),
                ('duracion_prorroga_min', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_checkin_min', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('descanso_entre_partidas_min', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_inicio_prevista', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_prevista', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROXIMAMENTE', 'Próximamente'), ('INSCRIPCIONES_ABIERTAS', 'Inscripciones abiertas'), ('PRORROGA', 'Prórroga'), ('INSCRIPCIONES_CERRADAS', 'Inscripciones cerradas'), ('PREPARADO', 'Preparado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=25)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('coeficiente_dificultad', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('modo_xp', models.CharField(choices=[('AUTOMATICA', 'Automática'), ('ESPECIAL', 'Especial')], default='AUTOMATICA', max_length=10)),
                ('multiplicador_xp_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('formato_competitivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torneos', to='torneos.formatocompetitivo')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torneos_organizados', to=settings.AUTH_USER_MODEL)),
                ('rango_maximo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_como_maximo', to='videojuegos.rangovideojuego')),
                ('rango_minimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_como_minimo', to='videojuegos.rangovideojuego')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torneos', to='videojuegos.videojuego')),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
        migrations.CreateModel(
            name='PremioTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='premios/')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='torneos.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('PROXIMAMENTE', 'Próximamente'), ('INSCRIPCIONES_ABIERTAS', 'Inscripciones abiertas'), ('PRORROGA', 'Prórroga'), ('INSCRIPCIONES_CERRADAS', 'Inscripciones cerradas'), ('PREPARADO', 'Preparado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], max_length=25)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROXIMAMENTE', 'Próximamente'), ('INSCRIPCIONES_ABIERTAS', 'Inscripciones abiertas'), ('PRORROGA', 'Prórroga'), ('INSCRIPCIONES_CERRADAS', 'Inscripciones cerradas'), ('PREPARADO', 'Preparado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], max_length=25)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_torneo', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='torneos.torneo')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
