# Generated by Django 6.1.1 on 2026-09-19 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
        ('videojuegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_historico', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('DESCALIFICADA', 'Descalificada')], default='CONFIRMADA', max_length=15)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('fecha_descalificacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_descalificacion', models.TextField(blank=True)),
                ('perfil_videojuego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='videojuegos.perfilvideojuegousuario')),
                ('rango_declarado_al_inscribirse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_historicas', to='videojuegos.rangovideojuego')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_torneo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('fecha_inscripcion',),
                'constraints': [models.UniqueConstraint(fields=('torneo', 'usuario'), name='unique_inscripcion_torneo_usuario')],
            },
        ),
    ]
