# Generated by Django 6.1.1 on 2026-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_inscripciontorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
