# Generated by Django 6.1.1 on 2026-09-21 11:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_torneo_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ronda_eliminado', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('es_campeon', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_finales', to='torneos.inscripciontorneo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='torneos.torneo')),
            ],
            options={
                'ordering': ('posicion', 'inscripcion__nick_historico'),
                'constraints': [models.UniqueConstraint(fields=('torneo', 'inscripcion'), name='unique_clasificacion_torneo_inscripcion')],
            },
        ),
    ]
