# Generated by Django 6.1.1 on 2026-10-05 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def completar_privados(apps, schema_editor):
    import secrets
    Torneo = apps.get_model('torneos', 'Torneo')
    Inscripcion = apps.get_model('torneos', 'InscripcionTorneo')
    Acceso = apps.get_model('torneos', 'AccesoTorneoPrivado')
    for torneo in Torneo.objects.filter(tipo='PRIVADO', codigo_acceso=''):
        torneo.codigo_acceso = secrets.token_urlsafe(18)
        torneo.save(update_fields=['codigo_acceso'])
    for inscripcion in Inscripcion.objects.filter(torneo__tipo='PRIVADO'):
        Acceso.objects.get_or_create(torneo_id=inscripcion.torneo_id, usuario_id=inscripcion.usuario_id)


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_clasificaciontorneo'),
        ('videojuegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoTorneoPrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('REVOCADO', 'Revocado')], default='ACTIVO', max_length=10)),
                ('fecha_acceso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('fecha_acceso',),
            },
        ),
        migrations.AddField(
            model_name='inscripciontorneo',
            name='reinscripciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='torneo',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'PRIVADO'), models.Q(('codigo_acceso', ''), _negated=True)), fields=('codigo_acceso',), name='unique_codigo_acceso_torneo_privado'),
        ),
        migrations.AddField(
            model_name='accesotorneoprivado',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_privados', to='torneos.torneo'),
        ),
        migrations.AddField(
            model_name='accesotorneoprivado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos_torneos_privados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accesotorneoprivado',
            constraint=models.UniqueConstraint(fields=('torneo', 'usuario'), name='unique_acceso_torneo_privado_usuario'),
        ),
        migrations.RunPython(completar_privados, migrations.RunPython.noop),
    ]
