# Generated by Django 6.1.1 on 2026-10-02 15:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0004_historialprogramacionpartida_checkinpartida'),
        ('torneos', '0004_clasificaciontorneo'),
        ('usuarios', '0003_historialkarma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('RESULTADO_INCORRECTO', 'Resultado incorrecto'), ('INCOMPARECENCIA', 'Incomparecencia'), ('CONDUCTA_INAPROPIADA', 'Conducta inapropiada'), ('TRAMPA', 'Posible trampa'), ('PROBLEMA_ARBITRAJE', 'Problema de arbitraje'), ('PROBLEMA_ORGANIZACION', 'Problema de organización'), ('OTRO', 'Otro problema')], max_length=32)),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('RESUELTA', 'Resuelta'), ('DESESTIMADA', 'Desestimada')], default='ABIERTA', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True)),
                ('notas_internas', models.TextField(blank=True)),
                ('hubo_sancion', models.BooleanField(default=False)),
                ('tipo_sancion', models.CharField(blank=True, choices=[('ADVERTENCIA', 'Advertencia'), ('LEVE', 'Leve'), ('MEDIA', 'Media'), ('GRAVE', 'Grave')], max_length=12)),
                ('karma_solicitado', models.SmallIntegerField(default=0)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_en_revision', to=settings.AUTH_USER_MODEL)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_creadas', to=settings.AUTH_USER_MODEL)),
                ('historial_karma', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_resuelta', to='usuarios.historialkarma')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='partidas.partida')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_resueltas', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='torneos.torneo')),
                ('usuario_denunciado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_creacion', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='HistorialDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('TOMA_REVISION', 'Tomada en revisión'), ('RESOLUCION', 'Resolución'), ('DESESTIMACION', 'Desestimación'), ('SANCION_APLICADA', 'Sanción aplicada')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('RESUELTA', 'Resuelta'), ('DESESTIMADA', 'Desestimada')], max_length=12)),
                ('estado_nuevo', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('RESUELTA', 'Resuelta'), ('DESESTIMADA', 'Desestimada')], max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='moderacion.denuncia')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_moderacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('fecha', 'pk'),
            },
        ),
    ]
