# Generated by Django 6.1.1 on 2026-09-19 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arbitraje', '0001_initial'),
        ('partidas', '0004_historialprogramacionpartida_checkinpartida'),
        ('torneos', '0003_torneo_fecha_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avisar_apertura_inscripciones', models.BooleanField(default=True)),
                ('avisar_novedades_torneos', models.BooleanField(default=True)),
                ('avisar_resultados_torneos', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA_INSCRIPCIONES', 'Apertura de inscripciones'), ('INVITACION_ARBITRAL', 'Invitación arbitral'), ('RESPUESTA_INVITACION', 'Respuesta a invitación'), ('ASIGNACION_PARTIDA', 'Asignación de partida'), ('REASIGNACION_PARTIDA', 'Reasignación de partida'), ('APERTURA_CHECKIN', 'Apertura de check-in'), ('CAMBIO_HORARIO', 'Cambio de horario'), ('RESULTADO_OFICIAL', 'Resultado oficial'), ('CANCELACION_TORNEO', 'Cancelación de torneo'), ('INTERVENCION_REQUERIDA', 'Intervención requerida')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('es_critica', models.BooleanField(default=False)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('clave_evento', models.CharField(blank=True, max_length=200)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('invitacion_arbitral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='arbitraje.arbitrotorneo')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='partidas.partida')),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='torneos.torneo')),
            ],
            options={
                'ordering': ('-fecha_creacion', '-pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('clave_evento', ''), _negated=True), fields=('destinatario', 'clave_evento'), name='unique_notificacion_evento_destinatario')],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='torneos.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_torneo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'torneo'), name='unique_seguimiento_usuario_torneo')],
            },
        ),
    ]
