# Generated by Django 6.1.1 on 2026-09-19 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneos', '0003_torneo_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ronda', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('posicion_en_siguiente_partida', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADA', 'Programada'), ('CHECK_IN', 'Check-in'), ('LISTA_PARA_COMENZAR', 'Lista para comenzar'), ('EN_CURSO', 'En curso'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('INCIDENCIA', 'Incidencia')], default='PENDIENTE', max_length=25)),
                ('fecha_hora_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_rivales_confirmados', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_apertura_checkin', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('codigo_lobby', models.CharField(blank=True, max_length=150)),
                ('contrasena_lobby', models.CharField(blank=True, max_length=150)),
                ('siguiente_partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas_anteriores', to='partidas.partida')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='torneos.torneo')),
            ],
            options={
                'ordering': ('numero_ronda', 'numero_orden'),
            },
        ),
        migrations.CreateModel(
            name='ParticipantePartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_partida', to='torneos.inscripciontorneo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='partidas.partida')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.UniqueConstraint(fields=('torneo', 'numero_ronda', 'numero_orden'), name='unique_partida_torneo_ronda_orden'),
        ),
        migrations.AddConstraint(
            model_name='participantepartida',
            constraint=models.UniqueConstraint(fields=('partida', 'inscripcion'), name='unique_inscripcion_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='participantepartida',
            constraint=models.UniqueConstraint(fields=('partida', 'posicion'), name='unique_posicion_por_partida'),
        ),
    ]
