# Generated by Django 6.1.1 on 2026-09-19 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
        ('torneos', '0003_torneo_fecha_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_declarado', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ganador_declarado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declaraciones_como_ganador', to='torneos.inscripciontorneo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones_resultado', to='partidas.partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaraciones_resultado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialResultadoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_anterior', models.CharField(blank=True, max_length=20)),
                ('resultado_nuevo', models.CharField(blank=True, max_length=20)),
                ('tipo_resultado_anterior', models.CharField(blank=True, max_length=25)),
                ('tipo_resultado_nuevo', models.CharField(max_length=25)),
                ('motivo', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ganador_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_ganador_anterior', to='torneos.inscripciontorneo')),
                ('ganador_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_ganador_nuevo', to='torneos.inscripciontorneo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_resultados', to='partidas.partida')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_resultado_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=20)),
                ('tipo_resultado', models.CharField(choices=[('NORMAL', 'Normal'), ('INCOMPARECENCIA', 'Incomparecencia'), ('DOBLE_INCOMPARECENCIA', 'Doble incomparecencia'), ('AVANCE_AUTOMATICO', 'Avance automático')], max_length=25)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_ganados', to='torneos.inscripciontorneo')),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado_oficial', to='partidas.partida')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_validados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
