# Generated by Django 6.1.1 on 2026-09-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitraje', '0001_initial'),
        ('partidas', '0002_declaracionresultado_historialresultadopartida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='arbitro_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_asignadas', to='arbitraje.arbitrotorneo'),
        ),
    ]
