# Generated by Django 6.1.1 on 2026-09-19 14:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_partida_arbitro_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProgramacionPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateTimeField(blank=True, null=True)),
                ('fecha_nueva', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_programacion_partida', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_programacion', to='partidas.partida')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARTICIPANTE', 'Participante'), ('ARBITRO', 'Árbitro o responsable')], max_length=15)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='partidas.partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins_partida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('partida', 'usuario', 'tipo'), name='unique_checkin_partida_usuario_tipo')],
            },
        ),
    ]
