# Generated by Django 6.1.1 on 2026-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_historialprogramacionpartida_checkinpartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprogramacionpartida',
            name='checkins_invalidados',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='instrucciones_lobby',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='partida',
            name='nombre_lobby',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
