# Generated by Django 6.1.1 on 2026-09-19 13:28

import django.core.validators
import django.utils.timezone
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('karma_total', models.PositiveIntegerField(default=100)),
                ('rol_global', models.CharField(choices=[('PLAYER', 'Jugador'), ('ADMIN', 'Administrador')], default='PLAYER', max_length=10)),
                ('estado_cuenta', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('BLOQUEADA', 'Bloqueada'), ('ELIMINADA', 'Eliminada')], default='ACTIVA', max_length=10)),
                ('disponible_para_arbitrar', models.BooleanField(default=False)),
                ('fecha_ultimo_cambio_nick', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('mostrar_ultima_conexion', models.BooleanField(default=False)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('mostrar_estado_online', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
    ]
