# Generated by Django 6.1.1 on 2026-09-21 13:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_clasificaciontorneo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_concedida', models.PositiveIntegerField()),
                ('xp_anterior', models.PositiveIntegerField()),
                ('xp_posterior', models.PositiveIntegerField()),
                ('nivel_anterior', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nivel_posterior', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('posicion_final', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tamano_torneo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('coeficiente_dificultad', models.DecimalField(decimal_places=3, max_digits=6)),
                ('multiplicador_especial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_xp', to='torneos.clasificaciontorneo')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_xp', to='torneos.inscripciontorneo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_xp', to='torneos.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('inscripcion',), name='unique_recompensa_xp_por_inscripcion')],
            },
        ),
    ]
