# Generated by Django 6.1.1 on 2026-10-01 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitraje', '0001_initial'),
        ('partidas', '0004_historialprogramacionpartida_checkinpartida'),
        ('torneos', '0004_clasificaciontorneo'),
        ('usuarios', '0002_historialxp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialKarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cantidad_solicitada', models.IntegerField()),
                ('karma_antes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('karma_despues', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo', models.CharField(choices=[('PARTICIPACION_COMPLETADA', 'Participación completada'), ('DECLARACION_VERAZ', 'Declaración veraz'), ('ARBITRAJE_COMPLETADO', 'Arbitraje completado'), ('ORGANIZACION_COMPLETADA', 'Organización completada'), ('AJUSTE_ADMINISTRATIVO', 'Ajuste administrativo'), ('SANCION_CONFIRMADA', 'Sanción confirmada')], max_length=32)),
                ('motivo', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('clave_idempotencia', models.CharField(max_length=200, unique=True)),
                ('arbitraje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_karma', to='arbitraje.arbitrotorneo')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_karma_autorizados', to=settings.AUTH_USER_MODEL)),
                ('historial_asignacion_arbitral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_karma', to='arbitraje.historialasignacionarbitro')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_karma', to='torneos.inscripciontorneo')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_karma', to='partidas.partida')),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_karma', to='torneos.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_karma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', '-pk'),
            },
        ),
    ]
