# Generated by Django 6.1.1 on 2026-09-19 14:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0002_declaracionresultado_historialresultadopartida_and_more'),
        ('torneos', '0003_torneo_fecha_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitroTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_invitacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('fecha_invitacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('activo_en_torneo', models.BooleanField(default=False)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_salida', models.TextField(blank=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitros', to='torneos.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_arbitraje', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAsignacionArbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_asignacion_arbitro', to=settings.AUTH_USER_MODEL)),
                ('arbitro_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_anterior', to='arbitraje.arbitrotorneo')),
                ('arbitro_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_nuevo', to='arbitraje.arbitrotorneo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_asignaciones_arbitro', to='partidas.partida')),
            ],
        ),
        migrations.AddConstraint(
            model_name='arbitrotorneo',
            constraint=models.UniqueConstraint(fields=('usuario', 'torneo'), name='unique_arbitro_por_torneo'),
        ),
    ]
