# Generated by Django 6.1.1 on 2026-09-19 13:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('genero', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='videojuegos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('instrucciones_competicion', models.TextField(blank=True)),
                ('plataformas', models.ManyToManyField(blank=True, related_name='videojuegos', to='videojuegos.plataforma')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='RangoVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='videojuegos.videojuego')),
            ],
            options={
                'ordering': ('videojuego', 'posicion'),
            },
        ),
        migrations.CreateModel(
            name='PerfilVideojuegoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_en_juego', models.CharField(max_length=150)),
                ('fecha_actualizacion_rango', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_videojuego', to=settings.AUTH_USER_MODEL)),
                ('rango_declarado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usuario', to='videojuegos.rangovideojuego')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_usuario', to='videojuegos.videojuego')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rangovideojuego',
            constraint=models.UniqueConstraint(fields=('videojuego', 'nombre'), name='unique_rango_nombre_por_videojuego'),
        ),
        migrations.AddConstraint(
            model_name='rangovideojuego',
            constraint=models.UniqueConstraint(fields=('videojuego', 'posicion'), name='unique_rango_posicion_por_videojuego'),
        ),
        migrations.AddConstraint(
            model_name='perfilvideojuegousuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'videojuego'), name='unique_perfil_usuario_videojuego'),
        ),
    ]
